version: "3.8"

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-admin-api"
    volumes:
      - /home/quelle/prometheus-grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - HOSTNAME="grafana.tomsplayground.de"
      - GF_RENDERING_SERVER_URL=http://grafana_renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_SMTP_ENABLED=${GF_SMTP_ENABLED}
      - GF_SMTP_HOST=${GF_SMTP_HOST}
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
    volumes:
      - /home/quelle/prometheus-grafana/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /home/quelle/prometheus-grafana/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - influxdb
      - renderer
    networks:
      - monitoring
      
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana_renderer
    restart: unless-stopped
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
    networks:
      - monitoring

volumes:
  prometheus_data: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/quelle/prometheus-grafana/prometheus_data
  grafana-storage: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/quelle/prometheus-grafana/grafana_data
  influxdb:

networks:
  monitoring:
    driver: bridge
