version: '3'

services:
  db:
    image: mariadb:11.4
    command: --innodb_read_only_compressed=OFF --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    user: "${PUID}:${PGID}"
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 8081:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  redis:
    image: redis
    restart: always

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/quelle/nextcloud/data/mysql
  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/quelle/nextcloud/data/nextcloud
